#!/usr/bin/env node
// build.js — concatenates src modules into a single app.js IIFE
// Usage:
//   node build.js              → dev build (unminified, fast)
//   node build.js --minify     → prod build (terser compressed, no mangle)
//   node build.js --watch      → dev build on every src change
// Output: dist/app.js

const fs   = require('fs');
const path = require('path');

const SRC    = path.join(__dirname, 'src');
const DIST   = path.join(__dirname, 'dist');
const MINIFY = process.argv.includes('--minify');
const WATCH  = process.argv.includes('--watch');

if (!fs.existsSync(DIST)) fs.mkdirSync(DIST);

// Module load order matters — each file can reference symbols from earlier files.
// Dependencies: config → state → utils → api → firebase → dom → tabs/* → app
const ORDER = [
  'config.js',
  'state.js',
  'utils.js',
  'api.js',
  'firebase.js',
  'dom.js',
  'ritual.js',
  'discord.js',
  'tabs/board.js',
  'tabs/player.js',
  'tabs/kingdom.js',
  'tabs/summary.js',
  'tabs/alerts.js',
  'tabs/nwgraph.js',
  'tabs/intel.js',
  'tabs/leaderboard.js',
  'tabs/kddb.js',
  'tabs/aistrategy.js',
  'tabs/tmmatchup.js',
  'app.js',
];

const VERSION = process.env.VERSION || 'dev-' + new Date().toISOString().slice(0, 10);

// Bootstrap prefix — reads token/server from IS session storage and launches app
const BOOTSTRAP = `
// ── BOOTSTRAP ───────────────────────────────────────────────────────────────
// Reads auth from the Intel Site's sessionStorage (same-origin access from bookmarklet)
const TOKEN    = window.__wp_token  || sessionStorage.getItem('Utopia-Token');
const _IS      = JSON.parse(localStorage.getItem('IntelState') || '{}');
const SERVER   = window.__wp_server || parseInt(_IS.server || '1');
const ENEMY_KD = _IS.enemyKd || '';

if (!TOKEN) { alert('Wave Planner: No token found. Open from intel.utopia.site.'); return; }
if (document.getElementById('__wp_overlay')) {
  // Tool already open — update enemy KD from IS in case it changed, then refresh
  const _newEnemy = _IS.enemyKd || S.eLoc;
  const _enemyChanged = _newEnemy && _newEnemy !== S.eLoc;
  document.getElementById('__wp_overlay').style.display = 'flex';
  if (_enemyChanged) {
    S.eLoc = _newEnemy;
    window.__wpA.refresh();
  }
  return;
}

// Inject into state before any other code runs
S.token  = TOKEN;
S.server = SERVER;
S.eLoc   = ENEMY_KD;

// Build the DOM then start
injectStyles();
buildOverlay();
window.__wpA.init();
`;

async function buildOnce() {
  const parts = ORDER.map(f => {
    const full = path.join(SRC, f);
    if (!fs.existsSync(full)) { console.error(`MISSING: ${f}`); process.exit(1); }
    const src  = fs.readFileSync(full, 'utf8');
    return MINIFY ? src : `\n// ═══ ${f} ═══\n${src}`;
  });

  const banner = `// Wave Planner v${VERSION} — built ${new Date().toISOString()}\n// DO NOT EDIT — generated by build.js from src/\n`;
  const body   = parts.join('\n') + '\n' + BOOTSTRAP;
  const iife   = `(function(){\n'use strict';\nconsole.log('[WavePlanner] v${VERSION} loaded');\n${body}\n})();\n`;

  let output;
  if (MINIFY) {
    const terser = require('terser');
    const result = await terser.minify(iife, {
      compress: { passes: 2, drop_console: false },
      // mangle: false — inline onclick handlers call functions by string name, mangling breaks them
      mangle: false,
      format: { comments: false },
    });
    if (!result.code) { console.error('Terser returned empty output'); process.exit(1); }
    output = banner + result.code + '\n';
  } else {
    output = banner + iife;
  }

  const outPath  = path.join(DIST, 'app.js');
  const tmpPath  = path.join(DIST, 'app.js.tmp');
  const bakPath  = path.join(DIST, 'app.js.bak');

  // Write to temp first — if anything goes wrong before the rename, the live
  // file is never touched.
  fs.writeFileSync(tmpPath, output, 'utf8');

  // Keep the last good build as a backup before replacing it.
  if (fs.existsSync(outPath)) fs.copyFileSync(outPath, bakPath);
  fs.renameSync(tmpPath, outPath);

  const lines = output.split('\n').length;
  const kb    = (Buffer.byteLength(output, 'utf8') / 1024).toFixed(1);
  const tag   = MINIFY ? ' (minified)' : '';
  console.log(`✓ Built dist/app.js — ${lines} lines, ${kb} KB${tag} (v${VERSION})`);
  if (fs.existsSync(bakPath)) {
    const bakKb = (fs.statSync(bakPath).size / 1024).toFixed(1);
    console.log(`  Previous build saved to dist/app.js.bak (${bakKb} KB)`);
  }
}

if (WATCH) {
  console.log('Watching src/ for changes (Ctrl-C to stop)...');
  buildOnce().catch(console.error);
  // Debounce: wait 200ms after last change before rebuilding
  let timer = null;
  fs.watch(SRC, { recursive: true }, () => {
    clearTimeout(timer);
    timer = setTimeout(() => buildOnce().catch(console.error), 200);
  });
} else {
  buildOnce().catch(e => { console.error(e); process.exit(1); });
}
