#!/usr/bin/env node
// build.js — concatenates src modules into a single app.js IIFE
// Usage: node build.js
// Output: dist/app.js

const fs   = require('fs');
const path = require('path');

const SRC  = path.join(__dirname, 'src');
const DIST = path.join(__dirname, 'dist');

if (!fs.existsSync(DIST)) fs.mkdirSync(DIST);

// Module load order matters — each file can reference symbols from earlier files.
// Dependencies: config → state → utils → api → firebase → dom → tabs/* → app
const ORDER = [
  'config.js',
  'state.js',
  'utils.js',
  'api.js',
  'firebase.js',
  'dom.js',
  'tabs/board.js',
  'tabs/player.js',
  'tabs/summary.js',
  'tabs/alerts.js',
  'tabs/leaderboard.js',
  'app.js',
];

const VERSION = process.env.VERSION || 'dev-' + new Date().toISOString().slice(0, 10);

// Bootstrap prefix — reads token/server from IS session storage and launches app
const BOOTSTRAP = `
// ── BOOTSTRAP ───────────────────────────────────────────────────────────────
// Reads auth from the Intel Site's sessionStorage (same-origin access from bookmarklet)
const TOKEN    = window.__wp_token  || sessionStorage.getItem('Utopia-Token');
const _IS      = JSON.parse(localStorage.getItem('IntelState') || '{}');
const SERVER   = window.__wp_server || parseInt(_IS.server || '1');
const ENEMY_KD = _IS.enemyKd || '5:3';

if (!TOKEN) { alert('Wave Planner: No token found. Open from intel.utopia.site.'); return; }
if (document.getElementById('__wp_overlay')) {
  document.getElementById('__wp_overlay').style.display = 'flex';
  return;
}

// Inject into state before any other code runs
S.token  = TOKEN;
S.server = SERVER;
S.eLoc   = ENEMY_KD;

// Build the DOM then start
injectStyles();
buildOverlay();
window.__wpA.init();
`;

// Gather module sources
const parts = ORDER.map(f => {
  const full = path.join(SRC, f);
  if (!fs.existsSync(full)) { console.error(`MISSING: ${f}`); process.exit(1); }
  const src  = fs.readFileSync(full, 'utf8');
  return `\n// ═══ ${f} ═══\n${src}`;
});

const banner = `// Wave Planner v${VERSION} — built ${new Date().toISOString()}\n// DO NOT EDIT — generated by build.js from src/\n`;
const body   = parts.join('\n') + '\n' + BOOTSTRAP;
const output = `${banner}(function(){\n'use strict';\nconsole.log('[WavePlanner] v${VERSION} loaded');\n${body}\n})();\n`;

const outPath = path.join(DIST, 'app.js');
fs.writeFileSync(outPath, output, 'utf8');

const lines = output.split('\n').length;
const kb    = (Buffer.byteLength(output, 'utf8') / 1024).toFixed(1);
console.log(`✓ Built dist/app.js — ${lines} lines, ${kb} KB (v${VERSION})`);
