// Wave Planner vdev-2026-05-12 — built 2026-05-12T11:58:52.436Z
// DO NOT EDIT — generated by build.js from src/
(function(){
'use strict';
console.log('[WavePlanner] vdev-2026-05-12 loaded');

// ═══ config.js ═══
// ── CONFIG ─────────────────────────────────────────────────────────────────
// All constants, data tables and CSS live here.
// Nothing in this file has side effects — safe to add to freely.

const CFG = {
  FB_PROJECT: 'utopia-leaderboard',
  FB_API_KEY: 'AIzaSyAnlkMabj-9a-fUEx66o86w2CnJaUgboIY',
  get FB_BASE() {
    return `https://firestore.googleapis.com/v1/projects/${this.FB_PROJECT}/databases/(default)/documents`;
  },
  API_BASE: 'https://api.intel.utopia.site',
};

// Duration ops (toggle on/off a province card)
const DOPS = [
  {c:'BLI',l:'Blizzard'},{c:'CHA',l:'Chaos'},{c:'DG',l:'Dragon'},
  {c:'DR',l:'Drought'},{c:'ET',l:'Exp Thieves'},{c:'EX',l:'Expose'},
  {c:'FOG',l:'Fog'},{c:'GL',l:'Gluttony'},{c:'GR',l:'Greed'},
  {c:'IR',l:'Inspire'},{c:'MW',l:'Mind Wipe'},{c:'MS',l:'Miser'},
  {c:'NF',l:'Night Fall'},{c:'PF',l:'Plague'},{c:'SW',l:'Shadow'},
  {c:'Slo',l:'Slow Burn'},{c:'Sto',l:'Storm'},{c:'Wra',l:'Wrath'},
];

// Instant ops
const IOPS = [
  {c:'AR',l:'Arson'},{c:'AMN',l:'Amnesia'},{c:'ARS',l:'Gr.Arson'},
  {c:'AW',l:'Assassin'},{c:'FB',l:'Fireball'},{c:'GA',l:'Grab Army'},
  {c:'INF',l:'Infiltrate'},{c:'KN',l:'Kidnap'},{c:'LS',l:'Learn'},
  {c:'MV',l:'Massacre'},{c:'NM',l:'Nightmare'},{c:'NS',l:'Night Strike'},
  {c:'PROP',l:'Propaganda'},{c:'RG',l:'Raze'},{c:'RV',l:'Reveal'},
  {c:'RT',l:'Riot'},{c:'SB',l:'Spy Bldgs'},{c:'SWH',l:'Switcharoo'},
  {c:'TOR',l:'Tornado'},{c:'WRi',l:'War Ritual'},
];

// Op type classification sets used by syncOps and leaderboard filtering
const OP_SETS = {
  // Intel / espionage ops — never tracked on leaderboard
  ESPIONAGE: new Set([
    'SPY_ON_THRONE','SPY_ON_MILITARY','SPY_ON_DEFENSE','SPY_ON_SCIENCES',
    'INFILTRATE','SURVEY_BUILDINGS','SNATCH_NEWS','SPY_ON_EXPLORATION','SHADOW_LIGHT',
    'ILLUMINATE_SHADOWS',
  ]),

  // Self-buff spells — never tracked on leaderboard
  SELF_BUFF: new Set([
    'TREE_OF_GOLD','BUILDERS_BOON','MAGIC_SHIELD','LOVE_AND_PEACE',
    'NATURES_BLESSING','FERTILE_LANDS','PATRIOTISM','MIND_FOCUS','GREATER_PROTECTION',
    'MINOR_PROTECTION','INSPIRE_ARMY','ANIMATE_DEAD','FOUNTAIN_OF_KNOWLEDGE',
    'MINERS_MYSTIQUE','GHOST_WORKERS','HEROES_INSPIRATION','SALVATION','REVELATION',
    'WRATH',
  ]),

  // Thievery sabotage ops — tracked on leaderboard
  THIEF_SAB: new Set([
    'ROB_THE_GRANARIES','ROB_THE_VAULTS','ROB_THE_TOWERS',
    'KIDNAP','ARSON','GREATER_ARSON','NIGHT_STRIKE','INCITE_RIOTS',
    'STEAL_WAR_HORSES','BRIBE_THIEVES','BRIBE_GENERALS','FREE_PRISONERS',
    'ASSASSINATE_WIZARDS','PROPAGANDA','SABOTAGE_WIZARDS','DESTABILIZE_GUILDS',
  ]),

  // Offensive spells — tracked on leaderboard
  OFFENSIVE_SPELL: new Set([
    'FIREBALL','LIGHTNING_STRIKE','LAND_LUST','TORNADOES','METEOR_SHOWERS',
    'DROUGHTS','STORMS','GLUTTONY','GREED','EXPOSE_THIEVES','BLIZZARD',
    'EXPLOSIONS','MYSTIC_VORTEX','NIGHTMARES','FOOLS_GOLD','PITFALLS',
    'CHASTITY','VERMIN','ABOLISH_RITUAL','SOUL_BLIGHT','MAGIC_WARD',
    'SLOTH','NIGHTFALL','AMNESIA',
  ]),
};

// Combined set of all ops we want to track on the leaderboard
// Anything NOT in this set gets skipped during syncOps
const TRACKED_OPS = new Set([...OP_SETS.THIEF_SAB, ...OP_SETS.OFFENSIVE_SPELL]);

const CSS = `
#__wp_overlay{position:fixed;inset:0;z-index:2147483647;background:#0a0c10;color:#c8d8e8;font-family:Rajdhani,sans-serif;display:flex;flex-direction:column;overflow:hidden}
#__wp_overlay *{box-sizing:border-box;margin:0;padding:0}
#__wph{background:#0f1218;border-bottom:1px solid #1e2d3d;height:48px;display:flex;align-items:center;padding:0 20px;gap:12px;flex-shrink:0}
#__wph .logo{font-family:monospace;font-size:16px;color:#00d4ff;letter-spacing:2px;flex:1}
.wb{padding:5px 12px;background:#151a22;border:1px solid #2a3f55;color:#7a9ab8;font-size:12px;font-weight:700;cursor:pointer;border-radius:3px;transition:all .15s}
.wb:hover{border-color:#00d4ff;color:#00d4ff}
.wb.g{border-color:#00cc66;color:#00ff88}.wb.g:hover{background:rgba(0,255,136,.1)}
.wb.r{border-color:#cc2233;color:#ff4455}.wb.r:hover{background:rgba(255,68,85,.1)}
#__wptb{background:#0f1218;border-bottom:1px solid #1e2d3d;display:flex;padding:0 20px;flex-shrink:0}
.wt{padding:10px 16px;font-size:11px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#4a6a88;cursor:pointer;border-bottom:2px solid transparent;margin-bottom:-1px;transition:all .15s}
.wt:hover{color:#7a9ab8}.wt.on{color:#00d4ff;border-bottom-color:#00d4ff}.wt.ong{color:#00ff88;border-bottom-color:#00ff88}
#__wptl{background:#0f1218;border-bottom:1px solid #1e2d3d;padding:8px 20px;display:flex;align-items:center;gap:10px;flex-wrap:wrap;flex-shrink:0}
.wkb{background:#151a22;border:1px solid #1e2d3d;border-radius:3px;padding:4px 10px;font-size:11px}
.wkb .l{color:#4a6a88;font-size:10px;font-weight:700;letter-spacing:1px;text-transform:uppercase}
.wkb .v{color:#c8d8e8;font-weight:600}.wkb .va{color:#00d4ff;font-family:monospace}
.wsav{font-family:monospace;font-size:11px;color:#4a6a88}
.wsav.ok{color:#00cc66}.wsav.err{color:#ff4455}.wsav.ing{color:#ffaa00}
#__wpbd{flex:1;overflow-y:auto;padding:16px 20px;position:relative}
.webar{display:flex;align-items:center;gap:10px;margin-bottom:14px;background:#0f1218;border:1px solid #1e2d3d;border-radius:4px;padding:10px 14px}
.webar label{font-size:10px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;white-space:nowrap}
.webar input{background:#151a22;border:1px solid #2a3f55;color:#c8d8e8;font-family:monospace;font-size:13px;padding:5px 8px;border-radius:3px;width:70px;outline:none}
.webar input:focus{border-color:#00d4ff}
.weboard{display:flex;gap:10px;overflow-x:auto;padding-bottom:10px;min-height:300px}
.wcol{background:#0f1218;border:1px solid #1e2d3d;border-radius:4px;width:220px;flex-shrink:0;display:flex;flex-direction:column}
.wcolh{padding:8px 10px;border-bottom:1px solid #1e2d3d;display:flex;align-items:center;gap:6px}
.wcolh input{background:transparent;border:none;color:#00d4ff;font-family:monospace;font-size:11px;letter-spacing:1px;outline:none;flex:1;min-width:0}
.wcolh input.ua{color:#4a6a88;pointer-events:none}
.wcnt{font-family:monospace;font-size:10px;color:#4a6a88;background:#151a22;border:1px solid #1e2d3d;padding:1px 5px;border-radius:2px}
.wdel{background:none;border:none;color:#4a6a88;cursor:pointer;font-size:13px;line-height:1;transition:color .15s}
.wdel:hover{color:#ff4455}
.wcolb{flex:1;padding:6px;display:flex;flex-direction:column;gap:3px;min-height:50px}
.wcolb.dov{background:rgba(0,212,255,.05)}
.wcard{background:#151a22;border:1px solid #1e2d3d;border-radius:3px;padding:7px 9px;cursor:grab;user-select:none;transition:border-color .15s}
.wcard:hover{border-color:#2a3f55}
.wcard.hop{border-left:2px solid #00d4ff}
.wcard.wdrag{opacity:.3}
.wct{display:flex;align-items:center;justify-content:space-between;margin-bottom:3px}
.wcn{font-size:12px;font-weight:700;color:#c8d8e8;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;max-width:130px}
.wcr{font-family:monospace;font-size:9px;color:#4a6a88}
.wcs{font-family:monospace;font-size:10px;color:#4a6a88;display:flex;gap:6px}
.wcs .def{color:#7a9ab8}.wcs .away{color:#00ff88}
.wtag{display:inline-block;font-family:monospace;font-size:9px;padding:1px 4px;border-radius:2px;background:rgba(0,212,255,.12);color:#00d4ff;border:1px solid rgba(0,212,255,.2);cursor:pointer;margin:1px}
.wtag:hover{background:rgba(255,68,85,.15);color:#ff4455}
.waddcol{width:42px;flex-shrink:0;background:#0f1218;border:1px dashed #2a3f55;border-radius:4px;cursor:pointer;display:flex;align-items:center;justify-content:center;color:#4a6a88;font-size:20px;transition:all .2s}
.waddcol:hover{border-color:#00d4ff;color:#00d4ff}
.wops{position:absolute;right:0;top:0;bottom:0;width:290px;background:#0f1218;border-left:1px solid #1e2d3d;transform:translateX(100%);transition:transform .2s;display:flex;flex-direction:column;overflow:hidden}
.wops.open{transform:none}
.wopsh{padding:12px 14px;border-bottom:1px solid #1e2d3d;display:flex;align-items:center;justify-content:space-between}
.wopsh h3{font-family:monospace;font-size:11px;color:#00d4ff;letter-spacing:1px}
.wopsb{flex:1;overflow-y:auto;padding:12px 14px}
.wopsec{font-size:10px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;margin:10px 0 6px}
.wopsg{display:grid;grid-template-columns:repeat(4,1fr);gap:4px}
.wop{padding:5px 3px;background:#151a22;border:1px solid #1e2d3d;color:#7a9ab8;font-family:monospace;font-size:9px;cursor:pointer;border-radius:2px;text-align:center;transition:all .12s}
.wop:hover{border-color:#00d4ff;color:#00d4ff}
.wop.sel{background:rgba(0,212,255,.12);border-color:#00d4ff;color:#00d4ff}
.wop.i:hover{border-color:#aa66ff;color:#aa66ff}
.wop.i.sel{background:rgba(170,102,255,.12);border-color:#aa66ff;color:#aa66ff}
.wsb{background:#151a22;border:1px solid #1e2d3d;border-radius:3px;padding:7px 9px;margin-bottom:6px}
.wsb .l{font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase}
.wsb .v{font-family:monospace;font-size:16px;color:#00d4ff}
.waf{color:#00ff88}.was{color:#00d4ff}.waw{color:#ffaa00}.wao{color:#ff4455}
.walt{display:flex;align-items:flex-start;gap:10px;padding:10px 14px;border-bottom:1px solid #1e2d3d;font-size:12px}
.wabg{font-family:monospace;font-size:9px;font-weight:700;padding:2px 6px;border-radius:2px;white-space:nowrap;flex-shrink:0;margin-top:1px}
.wau{background:rgba(255,68,85,.2);color:#ff4455;border:1px solid #cc2233}
.waw2{background:rgba(255,170,0,.2);color:#ffaa00;border:1px solid #cc8800}
.wai{background:rgba(0,212,255,.12);color:#00d4ff;border:1px solid #0099cc}
.wsum{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-bottom:16px}
.wscard{background:#0f1218;border:1px solid #1e2d3d;border-radius:4px;padding:12px 14px}
.wscard .l{font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;margin-bottom:4px}
.wscard .v{font-family:monospace;font-size:22px;color:#00d4ff}
.wscard .s{font-size:11px;color:#4a6a88;margin-top:2px}
.wtbl{width:100%;border-collapse:collapse;font-size:11px;background:#0f1218;border:1px solid #1e2d3d;border-radius:4px;overflow:hidden}
.wtbl th{background:#151a22;padding:7px 10px;text-align:left;font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;border-bottom:1px solid #1e2d3d}
.wtbl td{padding:7px 10px;border-bottom:1px solid #1e2d3d;font-family:monospace}
.wtbl tr:last-child td{border-bottom:none}
.wtbl tr:hover td{background:#151a22}
.wpc{background:#0f1218;border:1px solid #1e2d3d;border-radius:4px;margin-bottom:10px;overflow:hidden}
.wpch{padding:10px 14px;border-bottom:1px solid #1e2d3d;display:flex;align-items:center;justify-content:space-between}
.wpcb{padding:14px}
.wmatch{font-family:monospace;font-size:10px;padding:2px 7px;border-radius:2px;display:inline-block;margin:2px}
.wmyes{background:rgba(0,255,136,.12);color:#00ff88;border:1px solid #00cc66}
.wmno{background:rgba(255,68,85,.12);color:#ff4455;border:1px solid #cc2233}
.wmcl{background:rgba(255,170,0,.12);color:#ffaa00;border:1px solid #cc8800}
.wrole{display:flex;gap:6px;align-items:center}
.wrole span{font-size:10px;color:#4a6a88;font-weight:700;letter-spacing:1px;text-transform:uppercase}
.wpick{background:#151a22;border:1px solid #2a3f55;color:#c8d8e8;font-family:monospace;font-size:12px;padding:5px 8px;border-radius:3px;outline:none;cursor:pointer;max-width:180px}
.wpick:focus{border-color:#00d4ff}
.watk-card{background:#0f1218;border:1px solid #1e2d3d;border-radius:4px;margin-bottom:12px;overflow:hidden}
.watk-header{padding:12px 16px;border-bottom:1px solid #1e2d3d;background:#151a22;display:flex;align-items:center;justify-content:space-between}
.watk-wave{font-family:monospace;font-size:10px;color:#00d4ff;letter-spacing:1px}
.watk-body{padding:0}
.watk-row{display:flex;align-items:center;padding:10px 16px;border-bottom:1px solid #1e2d3d;gap:12px}
.watk-row:last-child{border-bottom:none}
.watk-num{font-family:monospace;font-size:22px;font-weight:700;color:#00d4ff;width:28px;flex-shrink:0;text-align:center}
.watk-main{flex:1;min-width:0}
.watk-target{font-size:15px;font-weight:700;color:#c8d8e8;margin-bottom:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.watk-detail{font-family:monospace;font-size:11px;color:#4a6a88;line-height:1.6}
.watk-gen{display:flex;flex-direction:column;align-items:center;flex-shrink:0;text-align:center}
.watk-gen-num{font-family:monospace;font-size:28px;font-weight:700;line-height:1}
.watk-gen-label{font-size:9px;font-weight:700;letter-spacing:1px;text-transform:uppercase;color:#4a6a88;margin-top:2px}
.watk-result{font-family:monospace;font-size:10px;padding:3px 8px;border-radius:2px;text-align:center;flex-shrink:0}
.watk-yes{background:rgba(0,255,136,.12);color:#00ff88;border:1px solid #00cc66}
.watk-cl{background:rgba(255,170,0,.12);color:#ffaa00;border:1px solid #cc8800}
.watk-no{background:rgba(255,68,85,.12);color:#ff4455;border:1px solid #cc2233}
.watk-ops{margin-top:4px;display:flex;flex-wrap:wrap;gap:3px}
.watk-summary{background:#151a22;border:1px solid #1e2d3d;border-radius:4px;padding:14px 16px;margin-bottom:16px;display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:10px}
.watk-sstat .l{font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;margin-bottom:3px}
.watk-sstat .v{font-family:monospace;font-size:20px;color:#00d4ff}
.watk-sstat .s{font-size:11px;color:#4a6a88;margin-top:1px}
.watk-noprov{color:#4a6a88;font-family:monospace;font-size:12px;padding:30px 0;text-align:center}
.watk-notarget{background:#0f1218;border:1px solid #1e2d3d;border-radius:4px;padding:24px;text-align:center;color:#4a6a88;font-family:monospace;font-size:12px}
.wspin{display:inline-block;width:28px;height:28px;border:2px solid #1e2d3d;border-top-color:#00d4ff;border-radius:50%;animation:__wpspin .7s linear infinite}
.wload{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:200px;gap:12px;color:#4a6a88;font-family:monospace;font-size:12px;letter-spacing:1px}
.wsech{font-family:monospace;font-size:10px;color:#4a6a88;letter-spacing:2px;text-transform:uppercase;margin-bottom:10px;padding-bottom:6px;border-bottom:1px solid #1e2d3d}
.wthr{background:#0f1218;border:1px solid #1e2d3d;border-radius:4px;padding:14px 16px;margin-bottom:16px}
.wthr-title{font-size:10px;font-weight:700;color:#4a6a88;letter-spacing:2px;text-transform:uppercase;margin-bottom:12px;display:flex;align-items:center;justify-content:space-between}
.wthr-title span{color:#ffaa00;font-size:10px;font-weight:400;letter-spacing:0;text-transform:none}
.wthr-row{display:flex;align-items:center;gap:10px;margin-bottom:10px}
.wthr-row:last-child{margin-bottom:0}
.wthr-label{font-size:12px;font-weight:700;color:#c8d8e8;width:50px;flex-shrink:0}
.wthr-input{background:#151a22;border:1px solid #2a3f55;color:#c8d8e8;font-family:monospace;font-size:13px;padding:5px 8px;border-radius:3px;width:110px;outline:none}
.wthr-input:focus{border-color:#ffaa00}
.wthr-hint{font-size:11px;color:#4a6a88;flex:1}
.wres-alert{background:rgba(255,170,0,.08);border:1px solid rgba(255,170,0,.2);border-radius:3px}
@keyframes __wpspin{to{transform:rotate(360deg)}}
`;


// ═══ state.js ═══
// ── STATE ──────────────────────────────────────────────────────────────────
// Single mutable state object shared across all modules.
// Add new fields here when features need persistent in-memory state.
// Never create module-local state that other modules need to read.

const S = {
  // Auth / server
  token: null,      // set during bootstrap
  server: 1,        // set during bootstrap

  // Loaded data
  own: null,        // OwnKingdom response
  enemy: null,      // EnemyKingdom response

  // War plan
  wpId: null,       // warPlanId from IS API
  cols: [],         // kanban columns [{title, items:[{id, province:{name,race,slot,requiredOps,notes}}]}]
  eLoc: '5:3',      // current enemy location string
  thresholds: { food: 0, gc: 0, runes: 0 },

  // UI state
  tab: 'board',
  drag: null,       // {ci, ii} during drag
  openSlot: null,   // {ci, ii} for ops panel
  role: 'leader',   // 'leader' | 'player'
  playerProv: null, // selected own province object
  lbView: 'damage', // leaderboard sort: 'damage'|'ops'|'gain'
};


// ═══ utils.js ═══
// ── UTILS ──────────────────────────────────────────────────────────────────
// Pure helper functions. No DOM access, no state mutation, no API calls.
// Safe to unit-test independently. Add helpers here freely.

/** Format a large number: 1234567 → "1.2M", 12345 → "12k" */
function fK(n) {
  if (n == null) return '—';
  if (n >= 1e6)  return (n / 1e6).toFixed(1) + 'M';
  if (n >= 1000) return Math.round(n / 1000) + 'k';
  return Math.round(n) + '';
}

/** Format seconds as human duration: 3700 → "1h1m", 90000 → "1d" */
function fA(s) {
  if (s == null) return '—';
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  if (h >= 48) return Math.floor(h / 24) + 'd';
  if (h > 0)   return h + 'h' + m + 'm';
  return m + 'm';
}

/** CSS class name for intel age colour: fresh=green, old=red */
function aC(s) {
  if (s == null) return 'wao';
  const h = s / 3600;
  if (h < 1)  return 'waf';
  if (h < 4)  return 'was';
  if (h < 12) return 'waw';
  return 'wao';
}

/** NW range check: can attacker NW a hit target NW? (75–133% rule) */
function canHit(attackerNW, targetNW) {
  const r = attackerNW / targetNW;
  return r >= 0.75 && r <= 1.33;
}

/** HTML-escape a string to prevent XSS in innerHTML strings */
function esc(s) {
  return (s || '').replace(/&/g,'&amp;').replace(/</g,'&lt;')
                  .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

/**
 * Look up the live enemy province object for a card's slot string.
 * slot may be "[18]" or 18 — normalised inside.
 */
function pd(slot) {
  if (!S.enemy) return null;
  const n = parseInt((slot + '').replace(/\[|\]/g, ''));
  return S.enemy.provinces.find(p => p.slot === n);
}

/** Shorthand for document.getElementById */
function $id(id) {
  return document.getElementById(id);
}

/** Update the save status indicator in the header */
function setSav(msg, cls) {
  const el = $id('__wpsav');
  if (el) {
    el.textContent = msg;
    el.className = 'wsav' + (cls ? ' ' + cls : '');
  }
}

/**
 * Safely render a tab content area.
 * Wraps the render function in try/catch so one broken tab can't crash others.
 * @param {string} elId  — DOM id of the tab content div
 * @param {Function} fn  — function that returns an HTML string
 */
function renderTab(elId, fn) {
  const el = $id(elId);
  if (!el) return;
  try {
    el.innerHTML = fn();
  } catch (e) {
    el.innerHTML = `<div class="wload" style="color:#ff4455">
      RENDER ERROR: ${esc(e.message)}<br>
      <span style="font-size:10px;color:#4a6a88">${esc(e.stack ? e.stack.split('\n')[1] : '')}</span>
    </div>`;
    console.error('[WavePlanner] render error in', elId, e);
  }
}

/** Loading spinner HTML — used while async data is in-flight */
function loadingHTML(msg) {
  return `<div class="wload"><div class="wspin"></div>${esc(msg || 'LOADING...')}</div>`;
}

/** Section heading HTML used in multiple tabs */
function sectionHead(label) {
  return `<div class="wsech">${esc(label)}</div>`;
}


// ═══ api.js ═══
// ── API ────────────────────────────────────────────────────────────────────
// All calls to api.intel.utopia.site live here.
// Functions are async and return parsed data or throw on failure.
// This is the only place that knows about BASE and H — add new endpoints here.

function _headers() {
  return { 'Utopia-Token': S.token, 'Content-Type': 'application/json' };
}

function _url(path) {
  return `${CFG.API_BASE}${path}`;
}

/** Fetch own kingdom data (SoT, SoM, SoS, Survey per province) */
async function fetchOwnKingdom() {
  const r = await fetch(_url(`/Kingdom/v1/OwnKingdom?server=${S.server}`), { headers: _headers() });
  if (!r.ok) throw new Error(`API ${r.status} — token may be expired. Reload the IS via game link.`);
  return r.json();
}

/** Fetch enemy kingdom data */
async function fetchEnemyKingdom(location) {
  const r = await fetch(_url(`/Kingdom/v1/EnemyKingdom?server=${S.server}&location=${location}`), { headers: _headers() })
    .catch(() => null);
  if (!r || !r.ok) return null;
  return r.json();
}

/** Fetch all op logs for the own kingdom (~24h window) */
async function fetchKingdomOps() {
  const r = await fetch(_url(`/Kingdom/v1/KingdomOps?server=${S.server}`), { headers: _headers() })
    .catch(() => null);
  if (!r || !r.ok) return null;
  return r.json();
}

/**
 * Create or update a war plan.
 * Pass an empty body {} to just get/create the warPlanId.
 * Pass {json, warPlanId} to save content.
 */
async function postWarPlan(location, body) {
  const r = await fetch(_url(`/WarPlan/v1/Post?server=${S.server}&location=${location}`), {
    method: 'POST',
    headers: _headers(),
    body: JSON.stringify(body || {}),
  });
  if (!r.ok) return null;
  return r.json();
}

/** Load a saved war plan by ID */
async function getWarPlan(location, warPlanId) {
  const r = await fetch(_url(`/WarPlan/v1/Get?server=${S.server}&location=${location}&warPlanId=${warPlanId}`), {
    headers: _headers(),
  });
  if (!r.ok) return null;
  return r.json();
}


// ═══ firebase.js ═══
// ── FIREBASE ───────────────────────────────────────────────────────────────
// Firestore REST API helpers. No SDK required — plain fetch.
// All functions return parsed JS objects, not raw Firestore field maps.

/** Convert a plain JS value to a Firestore field value */
function _toFB(v) {
  if (v === null || v === undefined) return { nullValue: null };
  if (typeof v === 'boolean') return { booleanValue: v };
  if (typeof v === 'number')  return Number.isInteger(v) ? { integerValue: String(v) } : { doubleValue: v };
  if (typeof v === 'string')  return { stringValue: v };
  if (v instanceof Set)       return { arrayValue: { values: [...v].map(_toFB) } };
  if (Array.isArray(v))       return { arrayValue: { values: v.map(_toFB) } };
  if (typeof v === 'object')  return { mapValue: { fields: Object.fromEntries(Object.entries(v).map(([k, val]) => [k, _toFB(val)])) } };
  return { stringValue: String(v) };
}

/** Convert a Firestore field value back to a plain JS value */
function _fromFB(v) {
  if (!v) return null;
  if ('stringValue'  in v) return v.stringValue;
  if ('integerValue' in v) return parseInt(v.integerValue);
  if ('doubleValue'  in v) return v.doubleValue;
  if ('booleanValue' in v) return v.booleanValue;
  if ('arrayValue'   in v) return (v.arrayValue.values || []).map(_fromFB);
  if ('mapValue'     in v) return Object.fromEntries(Object.entries(v.mapValue.fields || {}).map(([k, val]) => [k, _fromFB(val)]));
  return null;
}

function _fbUrl(path) {
  return `${CFG.FB_BASE}/${path}?key=${CFG.FB_API_KEY}`;
}

/** Write (PATCH/upsert) a document at path with plain JS data object */
async function fbWrite(path, data) {
  const fields = Object.fromEntries(Object.entries(data).map(([k, v]) => [k, _toFB(v)]));
  const r = await fetch(_fbUrl(path), {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ fields }),
  }).catch(() => null);
  if (!r) return null;
  return r.json();
}

/** Read a single document at path, returns plain JS object or null */
async function fbGet(path) {
  const r = await fetch(_fbUrl(path)).catch(() => null);
  if (!r || !r.ok) return null;
  return r.json();
}

/**
 * Query a collection with simple field filters.
 * filters: [{field, op, value}] — op defaults to 'EQUAL', value must be a string.
 * Returns array of plain JS objects (fields unwrapped from Firestore format).
 */
async function fbQuery(collection, filters = []) {
  const url = `${CFG.FB_BASE}:runQuery?key=${CFG.FB_API_KEY}`;
  const where = filters.map(f => ({
    fieldFilter: {
      field: { fieldPath: f.field },
      op: f.op || 'EQUAL',
      value: { stringValue: f.value },
    },
  }));
  const body = {
    structuredQuery: {
      from: [{ collectionId: collection }],
      where: filters.length === 1 ? where[0] : { compositeFilter: { op: 'AND', filters: where } },
      limit: 2000,
    },
  };
  const r = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  }).catch(() => null);
  if (!r || !r.ok) return [];
  const data = await r.json();
  return (data || [])
    .filter(d => d.document)
    .map(d => Object.fromEntries(Object.entries(d.document.fields || {}).map(([k, v]) => [k, _fromFB(v)])));
}


// ═══ dom.js ═══
// ── DOM ────────────────────────────────────────────────────────────────────
// Builds the overlay structure and injects styles.
// Called once during init. No business logic here.

function injectStyles() {
  const st = document.createElement('style');
  st.textContent = CSS;
  document.head.appendChild(st);

  const lk = document.createElement('link');
  lk.rel = 'stylesheet';
  lk.href = 'https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;600;700&display=swap';
  document.head.appendChild(lk);
}

function buildOverlay() {
  const ov = document.createElement('div');
  ov.id = '__wp_overlay';
  ov.innerHTML = `
<div id="__wph">
  <div class="logo">⚔ WAVE PLANNER</div>
  <div id="__wptick" style="font-family:monospace;font-size:11px;color:#4a6a88;display:none"></div>
  <div class="wrole">
    <span>View as:</span>
    <button class="wb" id="__wprole_leader" onclick="__wpA.setRole('leader')" style="border-color:#00d4ff;color:#00d4ff">⚔ Leader</button>
    <button class="wb" id="__wprole_player" onclick="__wpA.setRole('player')">🗡 Player</button>
  </div>
  <div id="__wpprovpick" style="display:none;align-items:center;gap:8px">
    <span style="font-size:10px;color:#4a6a88;font-weight:700;letter-spacing:1px;text-transform:uppercase">My Province:</span>
    <select class="wpick" id="__wpprovsel" onchange="__wpA.pickProv(this.value)">
      <option value="">— select —</option>
    </select>
  </div>
  <button class="wb g" id="__wpsavebtn" onclick="__wpA.save()">💾 Save</button>
  <button class="wb" onclick="__wpA.refresh()">↻ Refresh</button>
  <button class="wb r" onclick="document.getElementById('__wp_overlay').style.display='none'">✕ Close</button>
</div>

<div id="__wptl">
  <div class="wkb"><div class="l">Own KD</div><div class="v" id="__wpown">—</div></div>
  <div class="wkb"><div class="l">Enemy</div><div class="v va" id="__wpene">—</div></div>
  <div class="wkb"><div class="l">War</div><div class="v" id="__wpwar">—</div></div>
  <span class="wsav" id="__wpsav"></span>
</div>

<div id="__wptb">
  <div class="wt on"  id="__wpt_board"       onclick="__wpA.tab('board')">WAR BOARD</div>
  <div class="wt"     id="__wpt_player"      onclick="__wpA.tab('player')">MY ORDERS</div>
  <div class="wt"     id="__wpt_summary"     onclick="__wpA.tab('summary')">SUMMARY</div>
  <div class="wt"     id="__wpt_alerts"      onclick="__wpA.tab('alerts')">ALERTS<span id="__wpalc"></span></div>
  <div class="wt"     id="__wpt_leaderboard" onclick="__wpA.tab('leaderboard')">LEADERBOARD</div>
</div>

<div id="__wpbd">
  <div id="__wpc_board"></div>
  <div id="__wpc_player"      style="display:none"></div>
  <div id="__wpc_summary"     style="display:none"></div>
  <div id="__wpc_alerts"      style="display:none"></div>
  <div id="__wpc_leaderboard" style="display:none"></div>
  <div class="wops" id="__wpops"></div>
</div>`;

  document.body.appendChild(ov);

  // Close ops panel when clicking outside it
  $id('__wpbd').addEventListener('click', e => {
    const op = $id('__wpops');
    if (op.classList.contains('open') && !op.contains(e.target) && !e.target.closest('.wcard')) {
      op.classList.remove('open');
    }
  });
}


// ═══ tabs/board.js ═══
// ── TAB: BOARD ─────────────────────────────────────────────────────────────
// Kanban war board. Drag provinces into wave columns, assign ops.
// All functions that modify S.cols call renderBoard() to keep display in sync.

function renderBoard() {
  renderTab('__wpc_board', _buildBoard);
  // Restore enemy stats text if enemy is loaded
  if (S.enemy) {
    const tl = S.enemy.provinces.reduce((s, p) => s + (p.land || 0), 0);
    const es = $id('__wpestats');
    if (es) es.textContent = `${S.enemy.provinces.length} provs · ${fK(tl)} land`;
  }
}

function _buildBoard() {
  const enemyBar = `
    <div class="webar">
      <label>ENEMY:</label>
      <input id="__wpeloc" value="${esc(S.eLoc)}" placeholder="5:3">
      <button class="wb" style="font-size:11px"
        onclick="__wpA.loadEnemy($id('__wpeloc').value);__wpA.initCols();renderBoard();renderAlerts();renderSummary();renderPlayer()">
        LOAD
      </button>
      <div style="color:#00d4ff;font-weight:700;font-size:13px">${esc(S.enemy?.kingdomName || '—')}</div>
      <div style="font-size:11px;color:#4a6a88;margin-left:auto" id="__wpestats"></div>
    </div>`;

  let board = '<div class="weboard">';
  S.cols.forEach((col, ci) => {
    const ua = ci === 0; // Unassigned column is always index 0
    board += `
      <div class="wcol"
        ondragover="event.preventDefault();$id('__wpcb${ci}').classList.add('dov')"
        ondragleave="$id('__wpcb${ci}').classList.remove('dov')"
        ondrop="__wpA.drop(event,${ci})">
        <div class="wcolh">
          <input class="${ua ? 'ua' : ''}" value="${esc(col.title)}" ${ua ? 'readonly' : ''}
            onchange="S.cols[${ci}].title=this.value">
          <span class="wcnt">${col.items.length}</span>
          ${!ua ? `<button class="wdel" onclick="__wpA.delCol(${ci})">✕</button>` : ''}
        </div>
        <div class="wcolb" id="__wpcb${ci}">
          ${col.items.map((item, ii) => _buildCard(item, ci, ii)).join('')}
        </div>
      </div>`;
  });
  board += '<div class="waddcol" onclick="__wpA.addCol()">+</div></div>';

  return enemyBar + board;
}

function _buildCard(item, ci, ii) {
  const p   = pd(item.province.slot);
  const def = p?.calcs?.defPointsSummary?.defPointsHome || 0;
  const da  = p?.calcs?.defPointsSummary?.ageSeconds;
  const away = p?.som?.armiesAway?.length > 0;
  const ops  = item.province.requiredOps || [];

  return `
    <div class="wcard${ops.length ? ' hop' : ''}" draggable="true"
      ondragstart="__wpA.ds(event,${ci},${ii})"
      ondragend="this.classList.remove('wdrag')"
      onclick="__wpA.openOps(${ci},${ii})">
      <div class="wct">
        <div class="wcn">${esc(item.province.name)}</div>
        <div class="wcr">${esc(item.province.race || '')}</div>
      </div>
      <div class="wcs">
        ${def ? `<span class="def">${fK(def)}</span>` : ''}
        ${away ? '<span class="away">↗away</span>' : ''}
        ${da != null ? `<span class="${aC(da)}">${fA(da)}</span>` : ''}
      </div>
      ${ops.length ? `<div style="margin-top:4px">${ops.map(o =>
        `<span class="wtag" onclick="event.stopPropagation();__wpA.rmOp(${ci},${ii},'${o}')">${o}</span>`
      ).join('')}</div>` : ''}
    </div>`;
}

// ── Drag & drop ──
function boardDragStart(e, ci, ii) {
  S.drag = { ci, ii };
  e.currentTarget.classList.add('wdrag');
  e.dataTransfer.effectAllowed = 'move';
}

function boardDrop(e, ci) {
  e.preventDefault();
  $id('__wpcb' + ci)?.classList.remove('dov');
  if (!S.drag || S.drag.ci === ci) return;
  const item = S.cols[S.drag.ci].items.splice(S.drag.ii, 1)[0];
  S.cols[ci].items.push(item);
  S.drag = null;
  renderBoard();
  renderSummary();
}

// ── Column management ──
function addCol() {
  S.cols.push({ title: 'Wave ' + S.cols.length, items: [] });
  renderBoard();
}

function delCol(ci) {
  // Return items to unassigned before deleting
  S.cols[0].items.push(...S.cols[ci].items);
  S.cols.splice(ci, 1);
  renderBoard();
  renderSummary();
}

// ── Ops panel ──
function openOps(ci, ii) {
  S.openSlot = { ci, ii };
  const item = S.cols[ci].items[ii];
  const p    = pd(item.province.slot);
  const ops  = item.province.requiredOps || [];
  const def  = p?.calcs?.defPointsSummary?.defPointsHome;
  const da   = p?.calcs?.defPointsSummary?.ageSeconds;

  const html = `
    <div class="wopsh">
      <h3>// OPS</h3>
      <button onclick="__wpA.closeOps()" style="background:none;border:none;color:#4a6a88;cursor:pointer;font-size:16px">✕</button>
    </div>
    <div class="wopsb">
      <div style="font-size:15px;font-weight:700;margin-bottom:3px">${esc(item.province.name)}</div>
      <div style="font-family:monospace;font-size:10px;color:#4a6a88;margin-bottom:12px">
        ${esc(item.province.race || '')} · ${esc(p?.sot?.personality || '')} · Slot ${esc(item.province.slot)}
      </div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-bottom:10px">
        <div class="wsb"><div class="l">OPA</div><div class="v">${p?.sot?.opa || '—'}</div></div>
        <div class="wsb"><div class="l">DPA</div><div class="v">${p?.sot?.dpa || '—'}</div></div>
        <div class="wsb"><div class="l">Def Home</div><div class="v">${fK(def)}</div></div>
        <div class="wsb"><div class="l">Intel Age</div><div class="v"><span class="${aC(da)}">${fA(da)}</span></div></div>
      </div>
      ${p?.sot?.badSpells?.length ? `<div style="font-size:10px;color:#ff4455;margin-bottom:8px">⚠ ${p.sot.badSpells.map(s => s.name).join(', ')}</div>` : ''}
      ${p?.som?.armiesAway?.length ? `<div style="font-size:10px;color:#00ff88;margin-bottom:8px">↗ Army away — ${fA(p.som.armiesAway[0].secondsRemaining)} to return</div>` : ''}
      <div class="wopsec">Duration Ops</div>
      <div class="wopsg">
        ${DOPS.map(o => `<div class="wop${ops.includes(o.c) ? ' sel' : ''}" onclick="__wpA.togOp('${o.c}')" title="${esc(o.l)}">${esc(o.c)}</div>`).join('')}
      </div>
      <div class="wopsec">Instant Ops</div>
      <div class="wopsg">
        ${IOPS.map(o => `<div class="wop i${ops.includes(o.c) ? ' sel' : ''}" onclick="__wpA.togOp('${o.c}')" title="${esc(o.l)}">${esc(o.c)}</div>`).join('')}
      </div>
      <div class="wopsec">Notes</div>
      <textarea style="width:100%;background:#151a22;border:1px solid #2a3f55;color:#c8d8e8;font-family:monospace;font-size:10px;padding:6px;border-radius:2px;resize:vertical;min-height:50px;outline:none"
        onchange="__wpA.setNote(this.value)">${esc(item.province.notes || '')}</textarea>
    </div>`;

  $id('__wpops').innerHTML = html;
  $id('__wpops').classList.add('open');
}

function closeOps() {
  $id('__wpops').classList.remove('open');
  S.openSlot = null;
}

function togOp(c) {
  if (!S.openSlot) return;
  const { ci, ii } = S.openSlot;
  const item = S.cols[ci].items[ii];
  if (!item.province.requiredOps) item.province.requiredOps = [];
  const idx = item.province.requiredOps.indexOf(c);
  if (idx >= 0) item.province.requiredOps.splice(idx, 1);
  else          item.province.requiredOps.push(c);
  // Update button state in the already-open panel without full re-render
  document.querySelectorAll('#__wpops .wop').forEach(btn => {
    const bc = btn.getAttribute('onclick')?.match(/'([^']+)'/)?.[1];
    if (bc) btn.classList.toggle('sel', item.province.requiredOps.includes(bc));
  });
  renderBoard();
}

function rmOp(ci, ii, c) {
  const ops = S.cols[ci].items[ii].province.requiredOps || [];
  const i   = ops.indexOf(c);
  if (i >= 0) ops.splice(i, 1);
  renderBoard();
}

function setNote(v) {
  if (S.openSlot) S.cols[S.openSlot.ci].items[S.openSlot.ii].province.notes = v;
}

/** Seed initial columns from the loaded enemy kingdom */
function initCols() {
  if (!S.enemy) return;
  S.cols = [
    {
      title: 'Unassigned',
      items: S.enemy.provinces.map(p => ({
        id: Math.random().toString(36).slice(2),
        province: { id: p.id, name: p.name, race: p.race, slot: '[' + p.slot + ']' },
      })),
    },
    { title: 'Wave 1', items: [] },
    { title: 'Wave 2', items: [] },
  ];
}


// ═══ tabs/player.js ═══
// ── TAB: PLAYER ────────────────────────────────────────────────────────────
// "My Orders" tab — province picker + attack plan calculator.
// calcAttacks() is pure business logic, separated from the render function.

/**
 * Pure function: given a province, return an ordered attack plan.
 * Returns {attacks, totalGenerals, gensHome, best, reason}
 */
function calcAttacks(prov) {
  const waveTargets = S.cols.slice(1).flatMap(c => c.items.map(item => ({ ...item, waveName: c.title })));
  if (!waveTargets.length) return { attacks: [], reason: 'no_targets' };

  const aOff        = prov.som?.offPointsHome || 0;
  const aNW         = prov.networth || 0;
  const gensHome    = prov.som?.standingArmy?.generals ?? prov.sot?.generals ?? 5;
  const totalGenerals = 5; // standard max

  if (!aOff) return { attacks: [], reason: 'no_off' };

  // Score each wave target
  const scored = waveTargets.map(item => {
    const tp   = pd(item.province.slot);
    const tDef = tp?.calcs?.defPointsSummary?.defPointsHome || 0;
    const tNW  = tp?.networth || aNW || 1;
    const nwOk = canHit(aNW, tNW);
    const away = tp?.som?.armiesAway?.length > 0;
    const pct  = tDef > 0 ? aOff / tDef : 0;
    const dAge = tp?.calcs?.defPointsSummary?.ageSeconds;
    const score = (nwOk ? 100 : 0) + (pct > 1.01 ? 80 : 0) + (away ? 30 : 0)
                + (pct > 1.5 ? 20 : pct > 1.2 ? 10 : 0) - (tDef / 10000);
    return { item, tp, tDef, tNW, nwOk, away, breaks: pct > 1.01, pct, dAge, score, waveName: item.waveName };
  }).sort((a, b) => b.score - a.score);

  const best = scored.find(t => t.nwOk && t.breaks) || scored.find(t => t.nwOk) || scored[0];
  if (!best) return { attacks: [], reason: 'no_range' };

  /** Fewest generals needed to break a target (simplified linear scaling model) */
  function minGens(off, def, maxG) {
    if (!def || !off) return maxG;
    for (let n = 1; n <= maxG; n++) {
      if (off * (n / maxG) > def * 1.01) return n;
    }
    return maxG;
  }

  const breakable = scored.filter(t => t.nwOk && t.breaks);

  if (!breakable.length) {
    // Can't break anything clean — show best option with a warning
    const mg = minGens(aOff, best.tDef, totalGenerals);
    return {
      attacks: [{
        n: 1, target: best, gens: mg, result: 'marginal',
        pct: Math.round(best.pct * 100),
        note: 'Cannot cleanly break — consider waiting for enemy army to return or fresher intel',
      }],
      prov, totalGenerals, gensHome, best,
    };
  }

  // Greedy: assign generals across up to 5 attacks cycling through breakable targets
  const attacks = [];
  let gensAvailable = gensHome;
  const cycleTargets = [...breakable];

  for (let i = 0; i < Math.min(5, Math.max(gensAvailable, 1)); i++) {
    const t          = cycleTargets[i % cycleTargets.length];
    const mg         = minGens(aOff, t.tDef, totalGenerals);
    const actualGens = Math.min(mg, gensAvailable);
    const scaledOff  = aOff * (actualGens / totalGenerals);
    attacks.push({
      n:         attacks.length + 1,
      target:    t,
      gens:      actualGens,
      minGens:   mg,
      result:    scaledOff > t.tDef * 1.01 ? 'yes' : 'close',
      pct:       Math.round(scaledOff / (t.tDef || 1) * 100),
      scaledOff,
      note:      i > 0 ? 'Send after previous attack is away' : null,
    });
    gensAvailable -= actualGens;
    if (gensAvailable <= 0) break;
  }

  return { attacks, prov, totalGenerals, gensHome, best };
}

function renderPlayer() {
  renderTab('__wpc_player', _buildPlayer);
}

function _buildPlayer() {
  if (!S.own || !S.enemy) return '<div class="watk-noprov">Loading data...</div>';
  if (!S.playerProv)      return _buildProvPicker();

  const prov = S.playerProv;
  const { attacks, totalGenerals, gensHome, reason } = calcAttacks(prov);
  const waveTargets = S.cols.slice(1).flatMap(c => c.items);
  const aOff        = prov.som?.offPointsHome || 0;

  let h = _playerHeader(prov, aOff, gensHome, totalGenerals, waveTargets.length);

  if (!waveTargets.length) {
    return h + `<div class="watk-notarget">// No wave targets assigned yet<br>
      <span style="font-size:11px">The war leader needs to set targets in the WAR BOARD tab first</span></div>`;
  }
  if (reason === 'no_off') {
    return h + `<div class="watk-notarget">// No offensive data available for this province<br>
      <span style="font-size:11px">SoM data needed to calculate attacks</span></div>`;
  }
  if (!attacks.length) {
    return h + `<div class="watk-notarget">// No valid targets in NW range<br>
      <span style="font-size:11px">Your NW (${fK(prov.networth)}) doesn't overlap with any wave target</span></div>`;
  }

  // Group attacks by wave name
  const byWave = {};
  attacks.forEach(atk => {
    const wn = atk.target.waveName || 'Wave';
    if (!byWave[wn]) byWave[wn] = [];
    byWave[wn].push(atk);
  });

  h += `<div class="wsech">// ATTACK PLAN</div>`;
  Object.entries(byWave).forEach(([wave, list]) => {
    h += _buildAttackCard(wave, list, aOff, totalGenerals);
  });

  h += _buildContextTable(waveTargets, prov, aOff);
  return h;
}

function _buildProvPicker() {
  return `
    <div style="max-width:480px">
      <div class="wsech">// SELECT YOUR PROVINCE</div>
      <div style="display:grid;gap:8px">
        ${(S.own?.provinces || []).map(p => {
          const off  = p.som?.offPointsHome || p.sot?.offPoints || 0;
          const gens = p.som?.standingArmy?.generals ?? '?';
          return `<div onclick="__wpA.pickProv(${p.slot})"
            style="background:#151a22;border:1px solid #1e2d3d;border-radius:3px;padding:12px 14px;cursor:pointer;
                   display:flex;align-items:center;justify-content:space-between;transition:border-color .15s"
            onmouseover="this.style.borderColor='#2a3f55'" onmouseout="this.style.borderColor='#1e2d3d'">
            <div>
              <div style="font-size:14px;font-weight:700">${esc(p.name)}</div>
              <div style="font-family:monospace;font-size:10px;color:#4a6a88">${esc(p.race || '')} · ${esc(p.sot?.personality || '')}</div>
            </div>
            <div style="text-align:right">
              <div style="font-family:monospace;font-size:13px;color:#00d4ff">${fK(off)} off</div>
              <div style="font-family:monospace;font-size:10px;color:#4a6a88">${gens} gens home · ${fK(p.networth)} NW</div>
            </div>
          </div>`;
        }).join('')}
      </div>
    </div>`;
}

function _playerHeader(prov, aOff, gensHome, totalGenerals, targetCount) {
  const genColor = gensHome >= 3 ? '#00ff88' : gensHome >= 1 ? '#ffaa00' : '#ff4455';
  return `
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:16px">
      <div>
        <div style="font-size:18px;font-weight:700">${esc(prov.name)}</div>
        <div style="font-family:monospace;font-size:11px;color:#4a6a88">
          ${esc(prov.race || '')} · ${esc(prov.sot?.personality || '')} · ${fK(prov.networth)} NW
        </div>
      </div>
      <button onclick="__wpA.pickProv('')"
        style="padding:5px 10px;background:#151a22;border:1px solid #2a3f55;color:#7a9ab8;font-size:11px;font-weight:700;cursor:pointer;border-radius:3px">
        ↩ Change
      </button>
    </div>
    <div class="watk-summary">
      <div class="watk-sstat"><div class="l">Off Home</div><div class="v">${fK(aOff)}</div></div>
      <div class="watk-sstat"><div class="l">Generals Home</div>
        <div class="v" style="color:${genColor}">${gensHome}<span style="font-size:12px;color:#4a6a88"> / ${totalGenerals}</span></div>
      </div>
      <div class="watk-sstat"><div class="l">Own NW</div><div class="v">${fK(prov.networth)}</div></div>
      <div class="watk-sstat"><div class="l">Targets Set</div><div class="v">${targetCount}</div><div class="s">by war leader</div></div>
    </div>`;
}

function _buildAttackCard(wave, atkList, aOff, totalGenerals) {
  let h = `
    <div class="watk-card">
      <div class="watk-header">
        <span class="watk-wave">// ${esc(wave.toUpperCase())}</span>
        <span style="font-family:monospace;font-size:10px;color:#4a6a88">${atkList.length} attack${atkList.length > 1 ? 's' : ''}</span>
      </div>
      <div class="watk-body">`;

  atkList.forEach(atk => {
    const t         = atk.target;
    const away      = t.tp?.som?.armiesAway?.length > 0;
    const ops       = t.item.province.requiredOps || [];
    const da        = t.dAge;
    const genColor  = atk.gens <= 2 ? '#00ff88' : atk.gens <= 3 ? '#ffaa00' : '#c8d8e8';
    const resCls    = atk.result === 'yes' ? 'watk-yes' : atk.result === 'close' ? 'watk-cl' : 'watk-no';
    const resLabel  = atk.result === 'yes' ? 'BREAKS' : atk.result === 'close' ? 'CLOSE' : 'RISKY';
    const sentOff   = atk.scaledOff || aOff * (atk.gens / totalGenerals);

    h += `
      <div class="watk-row">
        <div class="watk-num" style="color:#4a6a88">${atk.n}</div>
        <div class="watk-main">
          <div class="watk-target">
            ${esc(t.item.province.name)}
            ${away ? ' <span style="color:#00ff88;font-size:11px">↗ army away</span>' : ''}
          </div>
          <div class="watk-detail">
            ${fK(t.tDef)} def · ${fK(sentOff)} off sent · ${atk.pct}% ratio
            ${da != null ? ` · intel <span class="${aC(da)}">${fA(da)}</span> old` : ''}
            ${atk.note ? `<br><span style="color:#ffaa00">⚠ ${esc(atk.note)}</span>` : ''}
          </div>
          ${ops.length ? `<div class="watk-ops">${ops.map(o => `<span class="wtag" style="cursor:default">${o}</span>`).join('')}</div>` : ''}
          ${t.item.province.notes ? `<div style="margin-top:4px;font-size:10px;color:#7a9ab8;background:#151a22;padding:4px 6px;border-radius:2px;border-left:2px solid #00d4ff">${esc(t.item.province.notes)}</div>` : ''}
        </div>
        <div class="watk-gen">
          <div class="watk-gen-num" style="color:${genColor}">${atk.gens}</div>
          <div class="watk-gen-label">generals</div>
        </div>
        <div class="watk-result ${resCls}">${resLabel}<br>${atk.pct}%</div>
      </div>`;
  });

  h += '</div></div>';
  return h;
}

function _buildContextTable(waveTargets, prov, aOff) {
  const rows = waveTargets.map(item => {
    const tp    = pd(item.province.slot);
    const tDef  = tp?.calcs?.defPointsSummary?.defPointsHome || 0;
    const tNW   = tp?.networth || 0;
    const nwOk  = canHit(prov.networth, tNW);
    const pct   = tDef > 0 ? Math.round(aOff / tDef * 100) : 0;
    const away  = tp?.som?.armiesAway?.length > 0;
    const cls   = !nwOk ? 'wmno' : aOff > tDef * 1.01 ? 'wmyes' : 'wmcl';
    return `<tr style="border-bottom:1px solid #1e2d3d">
      <td style="padding:6px 8px;font-weight:600">${esc(item.province.name)}</td>
      <td style="padding:6px 8px;font-family:monospace">${fK(tDef)}</td>
      <td style="padding:6px 8px;font-family:monospace">${fK(tNW)}</td>
      <td style="padding:6px 8px"><span class="wmatch ${cls}">${pct}%</span></td>
      <td style="padding:6px 8px"><span class="wmatch ${nwOk ? 'wmyes' : 'wmno'}">${nwOk ? '✓ in range' : '✗ out'}</span></td>
      <td style="padding:6px 8px">${away ? '<span style="color:#00ff88;font-family:monospace;font-size:10px">AWAY</span>' : '—'}</td>
    </tr>`;
  }).join('');

  return `
    <div style="margin-top:20px" class="wsech">// ALL WAVE TARGETS (context)</div>
    <table style="width:100%;border-collapse:collapse;font-size:11px">
      <thead><tr>
        <th style="text-align:left;padding:5px 8px;font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;border-bottom:1px solid #1e2d3d">Province</th>
        <th style="text-align:left;padding:5px 8px;font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;border-bottom:1px solid #1e2d3d">Def Home</th>
        <th style="text-align:left;padding:5px 8px;font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;border-bottom:1px solid #1e2d3d">NW</th>
        <th style="text-align:left;padding:5px 8px;font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;border-bottom:1px solid #1e2d3d">Off/Def</th>
        <th style="text-align:left;padding:5px 8px;font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;border-bottom:1px solid #1e2d3d">NW Range</th>
        <th style="text-align:left;padding:5px 8px;font-size:9px;font-weight:700;color:#4a6a88;letter-spacing:1px;text-transform:uppercase;border-bottom:1px solid #1e2d3d">Army</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
}

function pickProv(slot) {
  if (!slot) { S.playerProv = null; renderPlayer(); return; }
  S.playerProv = S.own.provinces.find(p => p.slot === parseInt(slot)) || null;
  renderPlayer();
}


// ═══ tabs/summary.js ═══
// ── TAB: SUMMARY ───────────────────────────────────────────────────────────

function renderSummary() {
  renderTab('__wpc_summary', _buildSummary);
}

function _buildSummary() {
  if (!S.own || !S.enemy) return '';

  const waveTargets = S.cols.slice(1).flatMap(c => c.items);
  const unassigned  = S.cols[0]?.items.length || 0;
  const attackers   = S.own.provinces.filter(p => (p.som?.offPointsHome || 0) > 0);
  const totalOff    = attackers.reduce((s, p) => s + (p.som?.offPointsHome || 0), 0);
  const totalDef    = S.enemy.provinces.reduce((s, p) => s + (p.calcs?.defPointsSummary?.defPointsHome || 0), 0);

  const summaryCards = `
    <div class="wsum">
      <div class="wscard"><div class="l">Targets</div><div class="v">${waveTargets.length}</div><div class="s">${unassigned} unassigned</div></div>
      <div class="wscard"><div class="l">Attackers</div><div class="v">${attackers.length}</div><div class="s">with SoM data</div></div>
      <div class="wscard"><div class="l">Total Off</div><div class="v">${fK(totalOff)}</div></div>
      <div class="wscard"><div class="l">Enemy Def</div><div class="v">${fK(totalDef)}</div><div class="s">known</div></div>
    </div>`;

  const rows = waveTargets.map(item => {
    const p     = pd(item.province.slot);
    const def   = p?.calcs?.defPointsSummary?.defPointsHome || 0;
    const da    = p?.calcs?.defPointsSummary?.ageSeconds;
    const ops   = item.province.requiredOps || [];
    const away  = p?.som?.armiesAway?.length > 0;
    const brk   = attackers.filter(a => canHit(a.networth, p?.networth || 1) && (a.som?.offPointsHome || 0) > def * 1.01).length;
    const pct   = attackers.length > 0 ? Math.round(brk / attackers.length * 100) : 0;
    const pctColor = pct >= 50 ? '#00ff88' : pct > 0 ? '#ffaa00' : '#ff4455';

    return `<tr>
      <td style="font-weight:700">${esc(item.province.name)}</td>
      <td style="color:#4a6a88">${esc(item.province.race || '')}</td>
      <td>${fK(def)}</td>
      <td>${ops.map(o => `<span class="wtag" style="cursor:default;font-size:8px">${o}</span>`).join('') || '—'}</td>
      <td>${brk}/${attackers.length} <span style="color:${pctColor}">(${pct}%)</span></td>
      <td><span class="${aC(da)}">${fA(da)}</span></td>
      <td>${away ? '<span style="color:#00ff88">AWAY</span>' : '—'}</td>
    </tr>`;
  }).join('');

  return `${summaryCards}
    ${sectionHead('Target Coverage')}
    <table class="wtbl">
      <thead><tr>
        <th>Province</th><th>Race</th><th>Def Home</th>
        <th>Ops</th><th>Breakers</th><th>Intel</th><th>Army</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
}


// ═══ tabs/alerts.js ═══
// ── TAB: ALERTS ────────────────────────────────────────────────────────────

function setThr(key, val) {
  S.thresholds[key] = parseInt(val) || 0;
  renderAlerts();
}

function renderAlerts() {
  renderTab('__wpc_alerts', _buildAlerts);
}

function _buildAlerts() {
  const thr = S.thresholds;
  const isLeader = S.role === 'leader';

  const settingsHtml = isLeader ? `
    <div class="wthr">
      <div class="wthr-title">
        Resource Alert Thresholds
        <span>Flag enemy provinces with resources ABOVE these limits</span>
      </div>
      <div class="wthr-row">
        <div class="wthr-label">Food</div>
        <input class="wthr-input" type="number" min="0" placeholder="0 = off"
          value="${thr.food || ''}" oninput="__wpA.setThr('food',this.value)">
        <div class="wthr-hint">e.g. 50000 — flag rich food targets for TM/fireball</div>
      </div>
      <div class="wthr-row">
        <div class="wthr-label">GC</div>
        <input class="wthr-input" type="number" min="0" placeholder="0 = off"
          value="${thr.gc || ''}" oninput="__wpA.setThr('gc',this.value)">
        <div class="wthr-hint">e.g. 100000 — good robbery/plunder target</div>
      </div>
      <div class="wthr-row">
        <div class="wthr-label">Runes</div>
        <input class="wthr-input" type="number" min="0" placeholder="0 = off"
          value="${thr.runes || ''}" oninput="__wpA.setThr('runes',this.value)">
        <div class="wthr-hint">e.g. 5000 — rich magic target</div>
      </div>
    </div>` : '';

  const al = _gatherAlerts(thr);

  // Update the badge on the Alerts tab button
  const ac = $id('__wpalc');
  if (ac) {
    ac.textContent = al.length ? ' (' + al.length + ')' : '';
    ac.style.color = al.some(a => a.c === 'u') ? '#ff4455' : '#ffaa00';
  }

  const resAlerts   = al.filter(a => a.c === 'r');
  const otherAlerts = al.filter(a => a.c !== 'r');
  let aHtml = '';

  if (resAlerts.length) {
    aHtml += `<div style="font-family:monospace;font-size:10px;color:#ffaa00;letter-spacing:2px;text-transform:uppercase;margin-bottom:8px">
      Resource Targets (${resAlerts.length})
    </div>`;
    aHtml += resAlerts.map(a => `
      <div class="walt" style="background:rgba(255,170,0,.06);border:1px solid rgba(255,170,0,.15);border-radius:3px;margin-bottom:4px">
        <span class="wabg" style="background:rgba(255,170,0,.2);color:#ffaa00;border:1px solid #cc8800">RESOURCE</span>
        <span>${a.t}</span>
      </div>`).join('');
  }

  if (otherAlerts.length) {
    if (resAlerts.length) aHtml += `<div style="font-family:monospace;font-size:10px;color:#4a6a88;letter-spacing:2px;text-transform:uppercase;margin:12px 0 8px">Military / Intel</div>`;
    aHtml += otherAlerts.map(a => `
      <div class="walt">
        <span class="wabg ${a.c === 'u' ? 'wau' : a.c === 'w' ? 'waw2' : 'wai'}">
          ${a.c === 'u' ? 'URGENT' : a.c === 'w' ? 'WARN' : 'INFO'}
        </span>
        <span>${a.t}</span>
      </div>`).join('');
  }

  if (!al.length) {
    aHtml = `<div style="color:#4a6a88;font-family:monospace;font-size:11px;padding:16px 0">
      // No active alerts${(thr.food || thr.gc || thr.runes) ? '' : ' — set thresholds above to enable resource alerts'}
    </div>`;
  }

  return settingsHtml + aHtml;
}

/** Build the flat list of alert objects from current state */
function _gatherAlerts(thr) {
  const al = [];

  if (S.enemy) {
    S.enemy.provinces.forEach(p => {
      const da  = p.calcs?.defPointsSummary?.ageSeconds;
      const age = da != null ? ` (intel ${fA(da)} old)` : '';

      // Resource thresholds
      if (p.sot) {
        const food = p.sot.food || 0, gc = p.sot.money || 0, runes = p.sot.runes || 0;
        if (thr.food > 0 && food > thr.food)
          al.push({ c: 'r', t: `<b>Food target:</b> ${esc(p.name)} has ${fK(food)} food (limit ${fK(thr.food)})${age} — TM/fireball` });
        if (thr.gc > 0 && gc > thr.gc)
          al.push({ c: 'r', t: `<b>GC target:</b> ${esc(p.name)} has ${fK(gc)} gc (limit ${fK(thr.gc)})${age} — robbery/plunder` });
        if (thr.runes > 0 && runes > thr.runes)
          al.push({ c: 'r', t: `<b>Runes target:</b> ${esc(p.name)} has ${fK(runes)} runes (limit ${fK(thr.runes)})${age} — magic drain` });
      }

      // Missing SoM on high-OPA province
      const opa = p.sot?.opa || 0;
      if (opa > 80 && !p.som)
        al.push({ c: 'w', t: `Missing SoM: <b>${esc(p.name)}</b> — ${opa} OPA attacker` });

      // Armies away
      p.som?.armiesAway?.forEach(a => {
        al.push({ c: 'i', t: `Army away: <b>${esc(p.name)}</b> — ${a.oSpecs || 0} oSpecs, ${a.land || 0} acres, ${a.secondsRemaining > 0 ? fA(a.secondsRemaining) + ' to return' : 'overdue'}` });
      });

      // No food
      if (p.sot && (p.sot.food || 1) === 0 && opa > 0)
        al.push({ c: 'u', t: `No food: <b>${esc(p.name)}</b>` });

      // Low GC
      if (p.sot && p.som && (p.sot.money || 0) < 1000)
        al.push({ c: 'w', t: `Low GC: <b>${esc(p.name)}</b> — ${fK(p.sot.money || 0)} gc` });

      // Stale intel (>8h)
      if (da != null && da > 28800)
        al.push({ c: 'w', t: `Stale intel: <b>${esc(p.name)}</b> — ${fA(da)} old` });
    });
  }

  if (S.own) {
    S.own.provinces.forEach(p => {
      p.som?.armiesAway?.forEach(a => {
        al.push({ c: 'i', t: `Own army away: <b>${esc(p.name)}</b> — ${a.secondsRemaining > 0 ? fA(a.secondsRemaining) + ' to return' : 'overdue'}` });
      });
      if (p.sot && (p.sot.money || 0) < 500)
        al.push({ c: 'u', t: `Own low GC: <b>${esc(p.name)}</b> — ${fK(p.sot.money || 0)} gc` });
    });
  }

  return al;
}


// ═══ tabs/leaderboard.js ═══
// ── TAB: LEADERBOARD ───────────────────────────────────────────────────────

function lbView(v) {
  S.lbView = v;
  renderLeaderboard();
}

async function renderLeaderboard() {
  const el = $id('__wpc_leaderboard');
  el.innerHTML = loadingHTML('LOADING LEADERBOARD...');

  try {
    const kdId = S.own?.location.replace(':', '_');
    const ops  = await fbQuery('ops', [{ field: 'kingdomId', value: kdId }]);

    if (!ops.length) {
      el.innerHTML = `<div style="color:#4a6a88;font-family:monospace;font-size:12px;padding:20px 0">
        // No op data yet — data accumulates automatically as players use the tool during war.
      </div>`;
      return;
    }

    el.innerHTML = _buildLeaderboard(ops);
  } catch (e) {
    el.innerHTML = `<div style="color:#ff4455;font-family:monospace;font-size:12px;padding:20px 0">
      Error loading leaderboard: ${esc(e.message)}
    </div>`;
  }
}

function _buildLeaderboard(ops) {
  // Aggregate by province
  const byProv = {};
  ops.forEach(op => {
    if (!op.provinceName) return;
    if (!byProv[op.provinceName]) byProv[op.provinceName] = {
      name: op.provinceName, totalOps: 0, successOps: 0,
      totalDamage: 0, totalGain: 0, opCounts: {}, opNames: {}, lastSeen: '',
    };
    const p = byProv[op.provinceName];
    p.totalOps++;
    if (op.success) p.successOps++;
    p.totalDamage += (op.damage || 0);
    p.totalGain   += (op.gain || 0);
    p.opCounts[op.opType] = (p.opCounts[op.opType] || 0) + 1;
    if (op.opName) p.opNames[op.opType] = op.opName;
    if (!p.lastSeen || op.utoDate > p.lastSeen) p.lastSeen = op.utoDate;
  });

  const sorted     = Object.values(byProv).sort((a, b) => b.totalDamage - a.totalDamage);
  const totalDmg   = sorted.reduce((s, p) => s + p.totalDamage, 0);
  const totalOps   = sorted.reduce((s, p) => s + p.totalOps, 0);
  const maxDmg     = sorted[0]?.totalDamage || 1;
  const successPct = totalOps > 0 ? Math.round(sorted.reduce((s, p) => s + p.successOps, 0) / totalOps * 100) : 0;

  const viewSorted = S.lbView === 'ops'   ? [...sorted].sort((a, b) => b.totalOps - a.totalOps)
                   : S.lbView === 'gain'  ? [...sorted].sort((a, b) => b.totalGain - a.totalGain)
                   : sorted;

  const header = `
    <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:14px">
      <div style="font-family:monospace;font-size:10px;color:#4a6a88;letter-spacing:2px;text-transform:uppercase">
        Kingdom Op Leaderboard — ${ops.length} ops logged
      </div>
      <div style="display:flex;gap:6px">
        <button class="wb${S.lbView === 'damage' ? ' g' : ''}" onclick="__wpA.lbView('damage')" style="font-size:10px;padding:3px 9px">Damage</button>
        <button class="wb${S.lbView === 'ops'    ? ' g' : ''}" onclick="__wpA.lbView('ops')"    style="font-size:10px;padding:3px 9px">Op Count</button>
        <button class="wb${S.lbView === 'gain'   ? ' g' : ''}" onclick="__wpA.lbView('gain')"   style="font-size:10px;padding:3px 9px">Gain</button>
      </div>
    </div>
    <div class="wsum" style="margin-bottom:16px">
      <div class="wscard"><div class="l">Total Ops Logged</div><div class="v">${fK(totalOps)}</div></div>
      <div class="wscard"><div class="l">Total Damage</div><div class="v">${fK(totalDmg)}</div></div>
      <div class="wscard"><div class="l">Active Provinces</div><div class="v">${sorted.length}</div></div>
      <div class="wscard"><div class="l">Success Rate</div><div class="v">${successPct}%</div></div>
    </div>`;

  const provRows = viewSorted.map((p, i) => {
    const pct     = p.totalOps > 0 ? Math.round(p.successOps / p.totalOps * 100) : 0;
    const topOp   = Object.entries(p.opCounts).sort((a, b) => b[1] - a[1])[0];
    const topName = topOp ? (p.opNames[topOp[0]] || topOp[0]) : '';
    const barW    = Math.round(p.totalDamage / maxDmg * 100);
    const medal   = i === 0 ? '🥇' : i === 1 ? '🥈' : i === 2 ? '🥉' : String(i + 1);
    const pctCol  = pct >= 70 ? '#00ff88' : pct >= 50 ? '#ffaa00' : '#ff4455';
    return `<tr>
      <td style="font-family:monospace;font-size:12px">${medal}</td>
      <td style="font-weight:700">${esc(p.name)}</td>
      <td style="text-align:right;font-family:monospace">
        ${fK(p.totalDamage)}
        <div style="height:3px;background:#1e2d3d;border-radius:2px;margin-top:2px">
          <div style="height:100%;width:${barW}%;background:#00d4ff;border-radius:2px"></div>
        </div>
      </td>
      <td style="text-align:right;font-family:monospace">${p.totalOps}</td>
      <td style="text-align:right;font-family:monospace;color:${pctCol}">${pct}%</td>
      <td style="text-align:right;font-family:monospace">${fK(p.totalGain)}</td>
      <td><span class="wtag" style="cursor:default;font-size:9px">${topName}${topOp ? ' ×' + topOp[1] : ''}</span></td>
      <td style="font-family:monospace;font-size:10px;color:#4a6a88">${esc(p.lastSeen || '')}</td>
    </tr>`;
  }).join('');

  const mainTable = `
    <table class="wtbl">
      <thead><tr>
        <th style="width:24px">#</th><th>Province</th>
        <th style="text-align:right">Damage</th><th style="text-align:right">Ops</th>
        <th style="text-align:right">Success%</th><th style="text-align:right">Gain</th>
        <th>Top Op</th><th>Last seen</th>
      </tr></thead>
      <tbody>${provRows}</tbody>
    </table>`;

  // Op breakdown table — grouped by category
  const byOp = {};
  ops.forEach(op => {
    if (!byOp[op.opType]) byOp[op.opType] = {
      count: 0, damage: 0, gain: 0,
      opName: op.opName || op.opType,
      category: op.category || (OP_SETS.THIEF_SAB.has(op.opType) ? 'thief_sabotage' : 'magic_offensive'),
    };
    byOp[op.opType].count++;
    byOp[op.opType].damage += op.damage || 0;
    byOp[op.opType].gain   += op.gain   || 0;
  });

  // Sort: thievery first then spells, within each by damage desc
  const opRows = Object.entries(byOp)
    .sort((a, b) => {
      if (a[1].category !== b[1].category) return a[1].category === 'thief_sabotage' ? -1 : 1;
      return b[1].damage - a[1].damage || b[1].count - a[1].count;
    })
    .map(([code, d]) => {
      const isThief = d.category === 'thief_sabotage';
      const catLabel = isThief
        ? `<span style="font-family:monospace;font-size:9px;padding:1px 4px;border-radius:2px;background:rgba(0,212,255,.12);color:#00d4ff;border:1px solid rgba(0,212,255,.2)">THIEF</span>`
        : `<span style="font-family:monospace;font-size:9px;padding:1px 4px;border-radius:2px;background:rgba(170,102,255,.12);color:#aa66ff;border:1px solid rgba(170,102,255,.2)">SPELL</span>`;
      return `<tr>
        <td><span class="wtag" style="cursor:default">${esc(code)}</span></td>
        <td style="color:#7a9ab8">${esc(d.opName || code)}</td>
        <td>${catLabel}</td>
        <td style="text-align:right;font-family:monospace">${d.count}</td>
        <td style="text-align:right;font-family:monospace">${fK(d.damage) || '—'}</td>
        <td style="text-align:right;font-family:monospace">${fK(d.gain) || '—'}</td>
      </tr>`;
    }).join('');

  const opTable = `
    <div style="margin-top:20px" class="wsech">Op Breakdown by Type</div>
    <table class="wtbl">
      <thead><tr>
        <th>Op</th><th>Full Name</th><th>Type</th>
        <th style="text-align:right">Count</th>
        <th style="text-align:right">Total Damage</th>
        <th style="text-align:right">Total Gain</th>
      </tr></thead>
      <tbody>${opRows}</tbody>
    </table>`;

  return header + mainTable + opTable;
}

// ── Silent op sync to Firebase ──────────────────────────────────────────────

/** Run on every init — silently syncs new ops since last watermark. Never blocks UI. */
async function syncOps() {
  if (!S.own) return;
  try {
    const ops = await fetchKingdomOps();
    if (!Array.isArray(ops) || !ops.length) return;

    const kdId   = S.own.location.replace(':', '_');
    const kdName = S.own.kingdomName || '';

    // Read the watermark
    const metaPath = `meta/${kdId}_watermark`;
    const metaDoc  = await fbGet(metaPath);
    let lastId     = 0;
    try { if (metaDoc?.fields?.lastSyncedId) lastId = parseInt(metaDoc.fields.lastSyncedId.integerValue || 0); } catch (e) {}

    const newOps = ops.filter(op => op.id && op.id > lastId);
    if (!newOps.length) {
      console.log(`[WavePlanner] Op sync — nothing new (watermark: ${lastId})`);
      return;
    }

    let synced = 0;
    let maxId  = lastId;

    for (const op of newOps) {
      if (!op.provinceName) continue;

      // Classify the op
      const isSelf      = op.provinceName === op.targetName;
      const isEspionage = OP_SETS.ESPIONAGE.has(op.opType);
      const isBuff      = OP_SETS.SELF_BUFF.has(op.opType) || isSelf;
      const isTracked   = TRACKED_OPS.has(op.opType);

      // Always advance the watermark so we don't re-process, but only
      // write to Firestore for ops we actually want on the leaderboard
      if (op.id > maxId) maxId = op.id;
      if (!isTracked) continue;

      const category = OP_SETS.THIEF_SAB.has(op.opType) ? 'thief_sabotage' : 'magic_offensive';

      const written = await fbWrite(`ops/${kdId}_${op.id}`, {
        opId:         op.id,
        kingdomId:    kdId,
        kingdomName:  kdName,
        server:       S.server,
        utoDate:      op.utoDate   || '',
        lastUpdated:  op.lastUpdated || '',
        slot:         op.slot      || 0,
        provinceName: op.provinceName || '',
        targetName:   op.targetName   || '',
        opType:       op.opType       || '',
        opName:       op.name || op.opType || '',
        category,
        result:       op.result  || 0,
        success:      op.result  === 1,
        damage:       op.damage  || 0,
        gain:         op.gain    || 0,
        syncedAt:     Date.now(),
      });

      if (written && !written.error) {
        synced++;
      }
    }

    if (maxId > lastId) {
      await fbWrite(metaPath, { kingdomId: kdId, lastSyncedId: maxId, updatedAt: Date.now() });
      console.log(`[WavePlanner] Synced ${synced} new ops (new watermark: ${maxId})`);
    }
  } catch (e) {
    console.log('[WavePlanner] Op sync failed:', e.message);
  }
}


// ═══ app.js ═══
// ── APP ────────────────────────────────────────────────────────────────────
// Top-level orchestration: init, refresh, save, tab switching, role, meta.
// This is the only file that touches window.__wpA.

window.__wpA = {

  // ── Initialisation ──────────────────────────────────────────────────────

  async init() {
    $id('__wpc_board').innerHTML = loadingHTML('FETCHING INTEL...');
    try {
      // Load own kingdom
      const od = await fetchOwnKingdom();
      S.own = od.kingdom;
      if (od.currentTick) {
        const t = $id('__wptick');
        t.textContent = `Tick ${od.currentTick.tickNumber} · ${od.currentTick.tickName}`;
        t.style.display = '';
      }

      // Create/load war plan
      const wp = await postWarPlan(S.own.location, {});
      if (wp) {
        S.wpId = wp.warPlanId;
        const plan = await getWarPlan(S.own.location, S.wpId);
        if (plan?.json) {
          try {
            const parsed = JSON.parse(plan.json);
            S.cols       = parsed.columns   || [];
            // IS current enemy (set from IntelState.enemyKd at startup) takes priority
            // Only fall back to saved plan location if IS had nothing loaded
            if (!S.eLoc || S.eLoc === '5:3') S.eLoc = parsed.enemyLocation || S.eLoc;
            S.thresholds = parsed.thresholds || S.thresholds;
          } catch (e) { /* malformed saved plan — start fresh */ }
        }
      }

      // Load enemy and seed cols if needed
      await this.loadEnemy(S.eLoc);
      if (!S.cols.length) initCols();

      // Render all tabs
      this.meta();
      renderBoard();
      renderAlerts();
      renderSummary();
      renderPlayer();
      this.setRole('leader');

      // Silent background op sync — never blocks UI
      syncOps();

    } catch (e) {
      $id('__wpc_board').innerHTML = `<div class="wload" style="color:#ff4455">ERROR: ${esc(e.message)}</div>`;
    }
  },

  // ── Data loading ────────────────────────────────────────────────────────

  async loadEnemy(loc) {
    const l = loc || $id('__wpeloc')?.value || '5:3';
    S.eLoc  = l;
    const d = await fetchEnemyKingdom(l);
    if (d) {
      S.enemy = d.kingdom;
      $id('__wpene').textContent = S.enemy.kingdomName || l;
      const tl = S.enemy.provinces.reduce((s, p) => s + (p.land || 0), 0);
      const es = $id('__wpestats');
      if (es) es.textContent = `${S.enemy.provinces.length} provs · ${fK(tl)} land`;
    }
  },

  async refresh() {
    $id('__wpc_board').innerHTML = loadingHTML('REFRESHING...');
    try {
      const od = await fetchOwnKingdom();
      S.own = od.kingdom;
      if (od.currentTick) {
        const t = $id('__wptick');
        t.textContent = `Tick ${od.currentTick.tickNumber} · ${od.currentTick.tickName}`;
      }
      await this.loadEnemy(S.eLoc);
      this.meta();
      renderBoard();
      renderAlerts();
      renderSummary();
      renderPlayer();
    } catch (e) { /* silent — board will show stale data */ }
  },

  // ── War plan persistence ────────────────────────────────────────────────

  async save() {
    if (!S.wpId) { setSav('No plan ID', 'err'); return; }
    setSav('Saving...', 'ing');
    try {
      const json = JSON.stringify({
        title:         'Wave Plan',
        content:       '',
        enemyLocation: S.eLoc,
        columns:       S.cols,
        thresholds:    S.thresholds,
      });
      const r = await postWarPlan(S.own.location, { json, warPlanId: S.wpId });
      setSav(r ? 'Saved ✓' : 'Failed', r ? 'ok' : 'err');
      if (r) setTimeout(() => setSav('', ''), 3000);
    } catch (e) {
      setSav('Error', 'err');
    }
  },

  // ── Header / meta ───────────────────────────────────────────────────────

  meta() {
    if (!S.own) return;
    $id('__wpown').textContent = S.own.kingdomName || S.own.location;
    const w = $id('__wpwar');
    if (S.own.war) { w.textContent = '⚔ WAR'; w.style.color = '#ff4455'; }
    else           { w.textContent = 'Peace'; w.style.color = '#7a9ab8'; }
  },

  // ── Tab switching ───────────────────────────────────────────────────────

  tab(t) {
    S.tab = t;
    ['board', 'player', 'summary', 'alerts', 'leaderboard'].forEach(x => {
      $id('__wpc_' + x).style.display = x === t ? '' : 'none';
      const el = $id('__wpt_' + x);
      el.className = 'wt' + (x === t ? (x === 'player' ? ' on ong' : ' on') : '');
    });
    // Trigger renders that are async or need fresh data
    if (t === 'player')      renderPlayer();
    if (t === 'summary')     renderSummary();
    if (t === 'alerts')      renderAlerts();
    if (t === 'leaderboard') renderLeaderboard();
  },

  // ── Role switching ──────────────────────────────────────────────────────

  setRole(role) {
    S.role = role;
    const isLeader = role === 'leader';

    $id('__wprole_leader').style.borderColor = isLeader ? '#00d4ff' : '';
    $id('__wprole_leader').style.color       = isLeader ? '#00d4ff' : '';
    $id('__wprole_player').style.borderColor = !isLeader ? '#00ff88' : '';
    $id('__wprole_player').style.color       = !isLeader ? '#00ff88' : '';

    $id('__wpsavebtn').style.display    = isLeader ? '' : 'none';
    $id('__wpprovpick').style.display   = isLeader ? 'none' : 'flex';

    if (!isLeader && S.own) {
      const sel = $id('__wpprovsel');
      sel.innerHTML = '<option value="">— select your province —</option>';
      S.own.provinces.forEach(p => {
        const opt     = document.createElement('option');
        opt.value     = p.slot;
        opt.textContent = p.name + (p.discord ? ' (' + p.discord + ')' : '');
        if (S.playerProv && S.playerProv.slot === p.slot) opt.selected = true;
        sel.appendChild(opt);
      });
    }

    if (!isLeader) this.tab('player');
    else           this.tab('board');
  },

  // ── Delegated public methods (called from inline onclick= in HTML) ──────
  // These thin wrappers keep window.__wpA as the single public API surface.

  initCols,
  ds:       boardDragStart,
  drop:     boardDrop,
  addCol,
  delCol,
  openOps,
  closeOps,
  togOp,
  rmOp,
  setNote,
  pickProv,
  setThr,
  lbView,
};


// ── BOOTSTRAP ───────────────────────────────────────────────────────────────
// Reads auth from the Intel Site's sessionStorage (same-origin access from bookmarklet)
const TOKEN    = window.__wp_token  || sessionStorage.getItem('Utopia-Token');
const _IS      = JSON.parse(localStorage.getItem('IntelState') || '{}');
const SERVER   = window.__wp_server || parseInt(_IS.server || '1');
const ENEMY_KD = _IS.enemyKd || '5:3';

if (!TOKEN) { alert('Wave Planner: No token found. Open from intel.utopia.site.'); return; }
if (document.getElementById('__wp_overlay')) {
  document.getElementById('__wp_overlay').style.display = 'flex';
  return;
}

// Inject into state before any other code runs
S.token  = TOKEN;
S.server = SERVER;
S.eLoc   = ENEMY_KD;

// Build the DOM then start
injectStyles();
buildOverlay();
window.__wpA.init();

})();
